# Things to note:
# Server must be restarted for changes in this file to take effect
# YAML syntax help:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

author:
  profile_picture: "./assets/images/headshot.jpg"
  name: Anders Gilliland
  username: Lion4567714

socials:
  - { platform: email,    preview: "lion@ablion.dev",    link: "mailto:lion@ablion.dev" }
  - { platform: github,   preview: "lion4567714",        link: "https://github.com/Lion4567714" }
  - { platform: linkedin, preview: "anders-gilliland",   link: "https://www.linkedin.com/in/anders-gilliland/" }

title: Lion's Blog
email: lion@ablion.dev
description: >- # this means to ignore newlines until "baseurl:"
  Blog + A place I play with fun web dev things.
  Still in the works, obviously.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ablion.dev" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

# What to show on the header
header_pages:
  - index.md
  - about.md

# How post URLs look
permalink: /:year/:title

# Build settings
plugins:
  - jemoji  # GitHub-style emojis
  - jekyll-feed
  - jekyll-seo-tag # Google search optimizations
  - jekyll-include-cache
  - jekyll-remote-theme # Downloads themes from rubygems.com rather than installing locally

# Uncomment remote_theme for production, theme for development
remote_theme: Lion4567714/lions-jekyll-theme
# theme: lions-jekyll-theme

google_analytics: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
